parser: "@typescript-eslint/parser"

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:react-hooks/recommended"
  - "plugin:prettier/recommended"
  - "prettier"

parserOptions:
  ecmaVersion: 2021
  sourceType: "module"
  project:
    - "./tsconfig.json"

env:
  es6: true
  browser: true
  es2021: true

plugins:
  - "@typescript-eslint"
  - "prettier"

rules:
  "prettier/prettier": "error"
  "@typescript-eslint/no-unused-vars": "error"
  "@typescript-eslint/no-explicit-any": "error"
  "react-hooks/rules-of-hooks": "error"
  "react-hooks/exhaustive-deps": "warn"

ignorePatterns:
  - "node_modules"
